[package]
name = "format"
version = "0.1.0"
authors = ["Jean Pierre Dudey <jeandudey@hotmail.com>"]

[dependencies]
varint = { path = "../varint" }
bytes = "0.4.6"
failure = "0.1.1"
failure_derive = "0.1.1"
