[package]
name = "xmr-format"
version = "0.1.0"
authors = ["Jean Pierre Dudey <jeandudey@hotmail.com>"]
license = "MIT/Apache-2.0"

[dependencies]
bytes = "0.4.6"

failure = "0.1.1"
failure_derive = "0.1.1"

xmr-varint = { path = "../varint" }
