[workspace]
members = [
    "chain",
    "crypto",
    "db",
    "dxmr",
    "hash",
    "keys",
    "network",
    "p2p",
    "portable-storage-utils",
    "portable-storage",
    "rct",
    "serialization",
]
