[package]
name = "xmr-verification"
version = "0.1.0"
authors = [
    "Jean Pierre Dudey <jeandudey@hotmail.com>",
    "Parity Technologies <admin@parity.io>"
]
license = "GPL-3.0-only"
include = ["LICENSE-APACHE", "LICENSE-GPL"]

[dependencies]
xmr-primitives = { path = "../primitives" }
