[package]
name = "hash"
version = "0.1.0"
authors = ["Jean Pierre Dudey <jeandudey@hotmail.com>"]

[dependencies]
portable-storage = { path = "../portable-storage" }
serialization = { path = "../serialization" }
failure = "0.1.1"
bytes = "0.4.6"
