[package]
name = "network"
version = "0.1.0"
authors = ["Jean Pierre Dudey <jeandudey@hotmail.com>"]

[dependencies]
chain = { path = "../chain" }
verification = { path = "../verification" }
primitives = { path = "../primitives" }
uuid = "0.5.0"
bytes = "0.4.6"
