[package]
name = "dxmr"
version = "0.1.0"
authors = ["Jean Pierre Dudey <jeandudey@hotmail.com>"]

[dependencies]
clap = "2.29.2"
failure = "0.1.1"
common_failures = "0.1.0"
log = "0.4.1"
env_logger = "0.5.0"
p2p = { path = "../p2p" }
db = { path = "../db" }
