[package]
name = "chain"
version = "0.1.0"
authors = ["Jean Pierre Dudey <jeandudey@hotmail.com>"]

[dependencies]
primitives = { path = "../primitives" }
keys = { path = "../keys" }
rct = { path = "../rct" }
format = { path = "../format" }
varint = { path = "../varint" }
bytes = "0.4.6"
