[package]
name = "chain"
version = "0.1.0"
authors = ["Jean Pierre Dudey <jeandudey@hotmail.com>"]

[dependencies]
hash = { path = "../hash" }
keys = { path = "../keys" }
rct = { path = "../rct" }
serialization = { path = "../serialization" }
